### ISSUE TITLE
Article text/background is too high-contrast

### ISSUE THREAD

**Issue by seandrickson** [chriscoyier/CSS-Tricks-v10#149]
The articles are causing unneeded eye strain by using pure black with pure white.

Ian Storm Taylor recommends [not using pure black](http://ianstormtaylor.com/design-tip-never-use-black/).

My recommendation is to change the both article body background, as well as, text color:

``` css
.module {
    color: #333;
    background-color: #EEE;
}
```
