### ISSUE TITLE
Border on Archive table broken

### ISSUE THREAD

**Issue by seandrickson** [chriscoyier/CSS-Tricks-v10#151]
I'm not exactly sure why this is an issue, but on Firefox 15, the table's border on the right side is breaking up on the [Archive's Page](http://css-tricks.com/archives/).

[See the screenshot of the problem here](https://www.dropbox.com/s/d8pm9ythsfbokx0/Screen%20Shot%202012-09-13%20at%2011.05.45%20AM.png).

My fix would be to add a border to the `<table>` element:

``` css
table {
    border: 1px solid rgb(204, 204, 204);
}
```
