### ISSUE TITLE
Cursor shows as text-select over search button

### ISSUE THREAD

**Issue by seandrickson** [chriscoyier/CSS-Tricks-v10#74]
When hovering the cursor over the search button, the cursor shows as a text-select cursor. Tested on Firefox 15. Issue does not appear on Webkit browsers.

Here's the fix:

``` css
.open-search { cursor: default; }
```
